FROM bitnami/spark:latest AS base

USER root
RUN install_packages curl
USER 1001

# RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.3.1.jar
# RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.901.jar
