# Generated by Django 5.1.3 on 2025-04-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databuilders", "0005_alter_datasample_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasample",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
