# Generated by Django 5.1.3 on 2025-04-09 20:15

import databuilders.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databuilders', '0004_databuilder_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasample',
            name='data',
            field=models.JSONField(blank=True, encoder=databuilders.encoders.PrettyJSONEncoder, null=True),
        ),
    ]
