# Generated by Django 5.1.3 on 2025-06-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databuilders", "0006_alter_datasample_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="databuilder",
            name="refresh_sample_task_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="databuilder",
            name="refresh_schema_task_id",
            field=models.UUIDField(null=True),
        ),
    ]
