# Generated by Django 5.1.3 on 2025-02-02 17:06

import datasources.encoders
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('CSV', 'CSV File'), ('JSON', 'JSON File'), ('XLSX', 'Excel File'), ('PARQUET', 'Parquet File'), ('POSTGRES', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('S3', 'Amazon S3')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('config', models.JSONField(encoder=datasources.encoders.PrettyJSONEncoder)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_data_sources', to=settings.AUTH_USER_MODEL)),
                ('users_with_access', models.ManyToManyField(blank=True, null=True, related_name='accessible_data_sources', to=settings.AUTH_USER_MODEL)),
                ('upload', models.FileField(blank=True, null=True, upload_to='temp_uploads/')),
            ],
        ),
    ]
