# Generated by Django 5.1.3 on 2025-02-05 15:54

from django.conf import settings
from django.db import migrations, models

import datasources.encoders


class Migration(migrations.Migration):

    dependencies = [
        (
            "datasources",
            "0001_initial_squashed_0004_alter_datasource_users_with_access",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="config",
            field=models.JSONField(
                blank=True, encoder=datasources.encoders.PrettyJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("FILE", "🗄️ File"),
                    ("POSTGRES", "🐘 PostgreSQL"),
                    ("MYSQL", "🐬 MySQL"),
                    ("S3", "☁️ S3"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="upload",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="users_with_access",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_data_sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
