# Generated by Django 5.1.3 on 2025-02-08 14:37

import datasources.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0007_alter_datasource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='schema',
            field=models.JSONField(blank=True, encoder=datasources.encoders.PrettyJSONEncoder, null=True),
        ),
    ]
