# Generated by Django 5.1.3 on 2025-06-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0009_commondatasourceconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="refresh_schema_task_id",
            field=models.UUIDField(null=True),
        ),
    ]
